apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-tracking-server
  namespace: ${NAMESPACE}
  labels:
    app: mlflow-tracking-server
    team: ${TEAM}
  annotations:
    # TODO: add these annotations later when we start using the GKE estafette extension
    # estafette.io/gcp-service-account: true
    # estafette.io/gcp-service-account-name: mlflow-tracking-server
    #
    # For now, we will add the needed annotation manually
    iam.gke.io/gcp-service-account: ${SERVICE_ACCOUNT}
